version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: AQA_TEST_SQL
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass